### ISSUE TITLE
Inconsistencies with User-Agent setting in SQLite sources

### ISSUE THREAD

**Issue by StephaneChatty** [osmandapp/OsmAnd-iOS#1775]
### Description

The documentation mentions the possibility to set the User-Agent header for tile sources described as SQLite databases. This feature is indeed useful e.g. for using tiles provided by IGN in France. Unfortunately, there are various discrepancies

- between the documentation and the code. The column name is "useragent" and not "userAgent" as documented at https://docs.osmand.net/ru/main@latest/development/osmand-file-formats/osmand-sqlite

- between Android and iOS. The feature seems present on Android and not on iOS.

- between app versions on iOS. Version 4.0.6 uses "OsmAnd%20Maps/4.0.6.3 CFNetwork/978.0.7 Darwin/18.7.0" as User-Agent, while version 4.1.1 apparently uses an empty User-Agent.

Consequently, it is impossible to use IGN sources with OsmAnd 4.1.1 on iOS.

### How to reproduce?

1- Create a SQLiteDB source file with a value associated to useragent
2- Load the source file in OsmAnd and display it
3- Setup a proxy (at the OS level on iOS, in the app on Android), display the User-Agent header in the proxy log
4- Observe the User-Agent that appears in the log while panning/zooming the map in OsmAnd
5- Repeat setps 2 to 4 on various versions of OsmAnd

### Your Environment
OsmAnd Version: 4.0.7, 4.1.1
Android/iOS version: both
Device model: iPhone SE, Samsung Galaxy S4

**Comment by rembac** [comment]
Hi,


It would be very nice if this bug could be solve. I am actually part of a mountain rescue service and we are considering using OSMAnd as our default app for our rescue ops. However, this bug actually prevent us to do so at this moment, because of the kind of maps we are using encounters this bug.

Thanks in advance to all the community who will help to solve this.
Best regards.

**Comment by PaulStets** [comment]
Please test in the next public TestFlight build. Should be fixed now.

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core/commit/5d48d3dddba70112feba871b7d4824bcf47245f7
https://github.com/osmandapp/OsmAnd/pull/15766

**Comment by rembac** [comment]
Dear Sir

I just downloaded last TestFlight Build and tried to test the map I am trying to use on iOS (and that is working already well in Android build).

However, It still seems remaining not to work.
Please find attached the map config file I am trying to use.

Best regards,


Rémi BACOT
French mountain Rescue team « PGHM SAVOIE »

**Comment by PaulStets** [comment]
Hi @rembac. Sorry, I should have been more clear. The changes will be available in the future build (4.0.3.34) and not in the current one. Thank you for understanding.

**Comment by rembac** [comment]
Good evening Sir,

I did test the next build 4.0.3.34 but the bug is still occurring. Did I miss something ?
Please find attached my config file I am using (and it works well) otherwise on an android phone.
Thanks a lot,

Remi BACOT

**Comment by StC-OSM** [comment]
After exploring a bit, I found that:
 - since version 4.2 on iOS, UserAgent is back to a meaningful value
 -  in version 4.2 it is still not settable through the useragent attribute in tile sources described in SQLite
 -  the useragent attribute is apparently ignored when used in the map_sources section of an OSF file

@rembac, I suspect that the third point above is what is hitting you. Since it was not in the original topic of this issue, it probably has not been addressed yet.

**Comment by rembac** [comment]
Trying to explain better my issues,

I am using a .osf config file. In the map_sources.json ,  it does contain items defining sql sources with specified urls .
The param userAgent of those are set to ““

That file works well on my Android OsmAnd device but is not working on the iPhone one.



On the other hand, I tried .sqlitedb on the iPhone (that works too on Android) and it’s not working either

**Comment by PaulStets** [comment]
Could you please clarify if use the empty user-agent field and it works differently on android and ios? If so, what is a correct behavior?

**Comment by rembac** [comment]
> After exploring a bit, I found that:
> 
> * since version 4.2 on iOS, UserAgent is back to a meaningful value
> * in version 4.2 it is still not settable through the useragent attribute in tile sources described in SQLite
> * the useragent attribute is apparently ignored when used in the map_sources section of an OSF file
> 
> @rembac, I suspect that the third point above is what is hitting you. Since it was not in the original topic of this issue, it probably has not been addressed yet.

You are perfectly right.

After retest, I now can display the map with the .sqlitedb file . 
Thus, It is not working with the same useragent param setted in the .osf file .


@PaulStets : I am afraid that I do not know what is the correct behavior between having the useragent param setted or not. However, I imagine that the bug as reported by @StephaneChatty  is effectively corrected and what I am reporting is something else, eventually misconfigured by myself (I cannot state on that point).

Thanks a lot anyway

**Comment by StC-OSM** [comment]
Some more exploring, with a little help from friends, shows that "useragent" does not work in OSF files but "userAgent" does. Still an inconsistency, but at least a way forward. Working on it.

**Comment by PaulStets** [comment]
While fixing the issue, I came across inconsistencies that might be confusing, but are explained by different naming conventions. The sqlite column is ```useragent```. The parameter name to create a map source is ```userAgent``` (this is the one to use in the .osf) and the parameter for the .metainfo file is called ```user_agent```.
Hope it clarifies it.

**Comment by rembac** [comment]
the three ways of spelling "useragent" are not working in my .osf file 
The mystery goes on...

**Comment by StC-OSM** [comment]
@rembac, I have sent you a private email with an OSF file that works for me and for another user, on Android AND on iOS.
