### ISSUE TITLE
Can't open Navigation settings

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2623]
### Description
Can't open Navigation settings (Can be opened via settings in the profile)

### Steps to reproduce
Navigation > Settings > Navigation settings

### Actual result

https://user-images.githubusercontent.com/104760013/222385154-631300a2-6e6d-47ec-979a-92e13a7d8def.MP4

### Expected result
Settings opening

### Your Environment
OsmAnd Version: 4.4.6.2
Android/iOS version: 15.7.3
Device model: iPad mini 4

**Comment by Zirochkabila** [comment]
4.4.6.5
iPhone XS
UI bug - when selecting the Customize route line menu


https://user-images.githubusercontent.com/104760013/224726547-fd035b6d-9ae2-477d-b851-23f3154742bb.mp4

**Comment by dmpr0** [comment]
Main issues should be fixed in 4.4.6.6

**Comment by Zirochkabila** [comment]
Still present 
4.4.6.6
iPhone XS

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2682

**Comment by Zirochkabila** [comment]
4.4.6.9
iPhone XS and iPad mini 4 - Still present

<table style="width:100%">
  <tr>
    <th>iPhone XS</th>
    <th>iPad mini 4</th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/226580581-beadadbf-1bb3-4ded-b646-3ab4c1512fd1.mov"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/226581031-46001a01-409c-4fa7-9ecf-12f8c378cd52.mp4"  width="300" height="auto"/> </td>
  </tr>
</table>
